# Generated by Django 4.1.4 on 2022-12-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='location',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='number',
        ),
        migrations.AddField(
            model_name='bird',
            name='migratory',
            field=models.CharField(choices=[('M', 'Migratory'), ('R', 'Residential')], default='M', max_length=1, verbose_name='migratory/residential'),
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Seen')),
                ('time', models.TimeField()),
                ('behavior', models.TextField(max_length=150)),
                ('number', models.IntegerField(default='1')),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bird')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
