# Generated by Django 4.1.4 on 2022-12-29 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sighting_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='location',
        ),
    ]
