# Generated by Django 4.1.4 on 2023-01-03 17:36

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_sighting_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', mapbox_location_field.models.LocationField(map_attrs={})),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='bird',
            name='locations',
            field=models.ManyToManyField(to='main_app.location'),
        ),
    ]
