# Generated by Django 4.1.4 on 2023-01-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_location_bird_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='locations',
        ),
        migrations.AddField(
            model_name='location',
            name='birds',
            field=models.ManyToManyField(to='main_app.bird'),
        ),
    ]
